### ISSUE TITLE
ServerName?

### ISSUE THREAD

**Issue by rkevinburton** [gildasio/docker-php-sqlsrv#1]
When I start a container that is derived from this container I get an error:

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message

**Comment by gildasio** [comment]
Hi, @rkevinburton !

It's not something very important to. There is any problem with this warning.

https://askubuntu.com/a/256018

But thank you for your report!
