### ISSUE TITLE
PDO Mysql

### ISSUE THREAD

**Issue by jorgejeferson** [gildasio/docker-php-sqlsrv#3]
Friend good night!
How can I add the mysql PDO drive and the sqlsrv

**Comment by gildasio** [comment]
Hi, @jorgejeferson !

PDO SQLSrv driver is already installed , look at [line 31](https://github.com/gjuniioor/docker-php-sqlsrv/blob/master/Dockerfile#L31).

To install PDO MySQL driver you can use this command inside the container ([like this answer](https://askubuntu.com/a/1000027)):

~~~
apt install php-mysql
~~~
