### ISSUE TITLE
Error on ODBC Driver

### ISSUE THREAD

**Issue by leolima** [gildasio/docker-php-sqlsrv#4]
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : TCP Provider: Error code 0x2746.
Sqlcmd: Error: Microsoft ODBC Driver 13 for SQL Server : Client unable to establish connection.

**Comment by gildasio** [comment]
Hi @leolima , sorry for the late.

How this errors appears and what is their collateral effects?

**Comment by leolima** [comment]
Hi @gildasio , no problem.

i executed the container in bridge mode to connect to a sql server in another machine on my local network.

then, the application tried to connect, but without success.
the sql server version is 2008.

the same application running on windows with sqlsrv drivers installed connect with successfull.

¯\_(ツ)_/¯

**Comment by gildasio** [comment]
@leolima do you have a local database copy?

If so can you connect docker normal running to that database? Just to test.

**Comment by leolima** [comment]
@gildasio found the problem.

the operational system is very old. 2008.
i have tested connecting to a sql server installed on a win 2012 and got success.

in my case, i probably will need migrate this legacy server to a newer server.

so, thank you. 
it was nice to talk about. May help someone

**Comment by gildasio** [comment]
Thanks for your feedback @leolima !

May be the authantication method need to be changed or something like that.
